site_name: "cashu-client docs"

theme:
  name: material
  
  icon:
    logo: material/peanut-outline

  features:
    - navigation.instant
    - navigation.tracking
    # turn this on if you want nav bar links
    - navigation.tabs 
  
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search

# page tree
nav:
  - Getting Started:
    - About: "index.md"
    - Install: "install.md"
  - Architecture: 
    - Cashu Protocol: "cashu.md"
    - Mint: "mint.md"
    - Swap: "swap.md"
    - Melt: "melt.md"
